first commit
alinashev/altexsoft-lab-2020 pull request #3
Opened 2020-08-19 08:01 UTC by alinashev

2020-08-20 18:55 UTC, serhii-shkodenko requested changes
Отсутствует реализация паттерна Repository и UnitOfWork. На усмотрение @alex-geraschenko, считать ли это дефектом, требущим исправления. От себя могу сказать, что в следующих заданиях умение применять эти паттерны как минимум пригодится, как максимум будет обязательным условием.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/AddNewRecipe.cs
> +        private Dictionary<string, Double> dictIngredients = new Dictionary<string, Double>();
В коде Вы используете, как псевдонимы для типов, так и полные их имена. Допускается делать либо так, либо так. При этом общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

Пожалуйста пройдитесь заменой по всему проекту и поправьте остальные случаи, в частности, для `String`, `Int32`.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/AddNewRecipe.cs
> +    public class AddNewRecipe : Folder
Для имен классов принято использовать имена существительные. 
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/AddNewRecipe.cs
> +            _pathIng.Append(GetPathFolder()).Append(_name).Append("Ingredient.json");
А что будет, если Вы захотите в какой-то момент поменять имена файлов, в которых Вы храните данные. Придется по всему проекту искать эти строки и менять. Лучше использовать отдельную сущность для таких целей.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/AddNewRecipe.cs
> +            int count = Convert.ToInt32(Console.ReadLine());
Что будет, если пользователь введет не цифру, а букву? Введенные пользователем принято проверять на корректность.  Обратите внимание на это в дальнейшем, здесь пока можно не фиксить.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/AddIngredients.cs
> +    public class AddIngredients : IJsonEditor
Для имен классов принято использовать имена существительные.
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/AddIngredients.cs
> +    public class AddIngredients : IJsonEditor
Имя класса подразумевает, что он будет заниматься добавлением ингридиентов, однако он занимается их хранением и записью на диск. Одновременное выполнение классом этих двух разных функций противоречит Single Responsibility принципу.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/AddNewRecipe.cs
> +    public class AddNewRecipe : Folder
Класс выполняет слишком много функций. В частности, класс, добавляющий рецепт, знает, в какой папке он должен храниться. Это противоречит Single Responsibility принципу.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/AddRecipe.cs
> +    public class AddRecipe: IJsonEditor
Неясна цель существования этого класса. Если он используется как модель данных, тогда он не должен сериалзовать их. Это противоречит Single Responsibility принципу.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/AddRecipe.cs
> +            File.WriteAllText(path, JsonConvert.SerializeObject(json, Formatting.Indented));
Что будет, если переданный как аргумент путь не существует?

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/Category.cs
> +    public class Category : Folder, IJsonToDictionary
Можно предположить, что данный класс должен служить как модель данных. Он хранит список категорий, при этом занимается чтением данных, их десериализацией, выводом на экран. Это нарушает Single Responsibility принцип.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/Category.cs
> +            _jsonString =File.ReadAllText( base.GetPathFolder() + "category.json");
А что будет, если Вы захотите в какой-то момент поменять имена файлов, в которых Вы храните данные. Придется по всему проекту искать эти строки и менять. Лучше использовать отдельную сущность для таких целей.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/Category.cs
> +            _jsonString =File.ReadAllText( base.GetPathFolder() + "category.json");
Что будет, если путь не существует?

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/Folder.cs
> +            return Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"jsons\");
А что будет, если Вы захотите в какой-то момент поменять имена файлов, в которых Вы храните данные. Придется по всему проекту искать эти строки и менять. Лучше использовать отдельную сущность для таких целей.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/IJsonToDictionary.cs
> +    public interface IJsonToDictionary
А что будет, если захотите поменять структуру Ваших данных? Имя лучше сделать более абстрактным.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/Ingredients.cs
> +    public class Ingredients: Folder, IJsonToDictionary
Еще одно нарушение Single Responsibility принципа. Класс читает данные, хранит результат чтения, знает, где данные хранятся, управляет их выводом в консоль. Если этот класс задумывался как модель данных, то его будет сложно использовать, например, в Xamarin приложении.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/Ingredients.cs
> +            _jsonString = File.ReadAllText( base.GetPathFolder() + "AllIngredient.json");
А что будет, если Вы захотите в какой-то момент поменять имена файлов, в которых Вы храните данные. Придется по всему проекту искать эти строки и менять. Лучше использовать отдельную сущность для таких целей.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/PrintRecipe.cs
> +            _jsonStringRecipeIngredient = File.ReadAllText( base.GetPathFolder() + select + "Ingredients" + ".json");
А что будет, если Вы захотите в какой-то момент поменять имена файлов, в которых Вы храните данные. Придется по всему проекту искать эти строки и менять. Лучше использовать отдельную сущность для таких целей.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/PrintRecipe.cs
> +    public class PrintRecipe: Folder, IJsonToDictionary
Класс предназначен для вывода рецепта, однако он еще и занимается чтением файла, знает о папке со всеми(!) данными приложения и хранит данные. Почитайте про Single Responsibility принцип.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/RecipeList.cs
> +            _jsonString = File.ReadAllText( base.GetPathFolder() + select + "Recipe" +  ".json");
Нет проверки существования файла.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/PrintRecipe.cs
> +            _jsonStringRecipeIngredient = File.ReadAllText( base.GetPathFolder() + select + "Ingredients" + ".json");
Не проверяется существование пути.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/AddRecipe.cs
> +    public class AddRecipe: IJsonEditor
Для имен классов принято использовать имена существительные.
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/MoveAddNewRecipe.cs
> +    public class MoveAddNewRecipe
Для имен классов принято использовать имена существительные.
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/MoveCategory.cs
> +    public class MoveCategory: IAction
Для имен классов принято использовать имена существительные.
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/MoveCategory.cs
> +        public string ChoiceCategory()
Приведите название метода в глагольную форму.
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/4df752aw(v=vs.71)

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/MoveCategory.cs
> +        public string ChoiceSubCategory()
Приведите название метода в глагольную форму.
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/4df752aw(v=vs.71)

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/MoveCategory.cs
> +        public string ChoiceRecipe()
Приведите название метода в глагольную форму.
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/4df752aw(v=vs.71)

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/Router.cs
> +        public void Selection()
Приведите название метода в глагольную форму.
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/4df752aw(v=vs.71)

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/RecipeList.cs
> +    public class RecipeList : Folder, IJsonToDictionary
Почитайте про Single Responsibility принцип. Класс выполняет слишком много функций.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/Subcategory.cs
> +    public class Subcategory: Folder, IJsonToDictionary
Почитайте про Single Responsibility принцип.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/Subcategory.cs
> +            jsonString = File.ReadAllText(base.GetPathFolder() + select + "Subcategory" +  ".json");
Нет проверки существования файла.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/PrintRecipe.cs
> +        public void JsonToDictionary()
Во всех подобных классах есть одинаковые методы. Возможно Вам пригодятся дженерики, либо наследование от общего предка. https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/generics/

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/Program.cs
> +            Router router = new Router();
На машине с английской локалью Ваша программа запускается так:
![encoding_error_alinashev](https://user-images.githubusercontent.com/69808191/90812449-cfa63b00-e32e-11ea-843d-b53573d3154b.png)

Поправьте кодировку для консоли.

2020-08-20 18:55 UTC, serhii-shkodenko commented on task2/PrintRecipe.cs
> +            _jsonStringRecipe = File.ReadAllText( base.GetPathFolder() + select + ".json");
Нет проверки пути.

2020-08-20 18:59 UTC, serhii-shkodenko commented
Еще одно замечание: в ветке почему-то отсуствует файл проекта. Еще рекоммендую поменять файл .gitignore на например вот этот https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

2020-08-21 07:52 UTC, serhii-shkodenko commented
Небольшое дополнение. Видимо, те классы, которые нарушают Single Responsibility принцип, задумывались как некие менеджеры. Если это так, почитайте про Dependency Injection.

2020-08-21 15:32 UTC, alex-geraschenko commented
> Отсутствует реализация паттерна Repository и UnitOfWork. На усмотрение @alex-geraschenko, считать ли это дефектом, требущим исправления. От себя могу сказать, что в следующих заданиях умение применять эти паттерны как минимум пригодится, как максимум будет обязательным условием.

Я бы не сказал, что это дефект. Скорее, реализация этого шаблона позволит лучше структурировать код, улучшит взаимодействие сущностей и позволит лучше понять, как делать последующие задания

2020-08-21 15:38 UTC, alex-geraschenko commented
Еще я бы обратил внимание на организацию файлов. Постарайтесь разнести файлы по разным подпапкам типа `Models`, `Repositories` и т.п.

2020-08-26 14:13 UTC, alinashev commented
Добрый день. Для нормальной работы программы после клонирования переместите, пожалуйста, папку Book в Debug/Release

2020-08-26 17:42 UTC, serhii-shkodenko commented
@alinashev Файлы так и не разнесены по подпапкам. Файла проекта тоже нет. Чтобы файлы были доступны после билда: ПКМ -> Properties -> Copy if newer.

2020-08-26 17:44 UTC, serhii-shkodenko commented
Не все замечания помеченыя как Resolved. Просмотрите их, пожалуйста, и отметьте, кнопкой те, которые Вы уже поправили.

2020-08-26 17:54 UTC, serhii-shkodenko requested changes

2020-08-26 17:54 UTC, serhii-shkodenko commented on task2/Ingredients.cs
> +    public class Ingredient : IJsonEditor
Имя класса подразумевает, что это модель, которая будет хранить данные для иодного ингридиента. В то же время есть только публичное свойство в множественном числе и неясно, что оно хранит. Кроме того, класс управляет сериализацией данных. Класс модели не следует делать таким "мастером на все руки". Почитайте про Single Responsibility принцип. Пожалуйста, пройдителсь по всем остальным похожим случаям и поправьте.

2020-08-26 17:54 UTC, serhii-shkodenko commented on task2/Ingredients.cs
> +            File.WriteAllText(path, JsonConvert.SerializeObject(json, Formatting.Indented));
Что будет, если путь не существует? Да, выше в коде вы проверяете директорию, но метод у Вас публичный, потребитель может положиться на Вашу реалиацию не проверить путь.

2020-08-27 11:13 UTC, serhii-shkodenko commented
@alinashev Алина, пожалуйста, отметье кнопкой "Resolve conversation" те замечения, которые Вы исправили.

2020-08-27 11:17 UTC, alinashev commented
> @alinashev Алина, пожалуйста, отметье кнопкой "Resolve conversation" те замечения, которые Вы исправили.
Я кардинально изменила проект. Резолвить ли замечания связанные с самым первым вариантом, что я коммитила?

2020-08-27 11:19 UTC, serhii-shkodenko commented
> > @alinashev Алина, пожалуйста, отметье кнопкой "Resolve conversation" те замечения, которые Вы исправили.
> > Я кардинально изменила проект. Резолвить ли замечания связанные с самым первым вариантом, что я коммитила?

Да. Потому что складывается впечатление, что они не исправлены.

2020-08-27 11:21 UTC, serhii-shkodenko commented on task2/Controller/AllIngredients.cs
> +        private  FileWriter _fileWriter = new FileWriter();
Почитайте про Dependency Inversion Principle. Найдите похожие места в коде и поправьте их в соответствии с этим принципом.

2020-08-27 11:35 UTC, alinashev commented on task2/Controller/AllIngredients.cs
> +        private  FileWriter _fileWriter = new FileWriter();
Проблемы с Dependency Inversion встречается в двух классах AllIngredients и MoveAddRecipe. Второй класс реализует интерфейс IAction(нужен для паттерна Command) и в случае избежания проблемы принципа Dependency Inversion мы упираемся в проблему Single Responsibility

2020-08-27 11:43 UTC, serhii-shkodenko commented on task2/Controller/AllIngredients.cs
> +    public class AllIngredients
Класс лучше переназвать. Его имя наталкивает на мысль, что это модель. Однако он занимается обновлением данных. Так и назовите его.

2020-08-28 06:17 UTC, serhii-shkodenko requested changes

2020-08-28 06:17 UTC, serhii-shkodenko commented on task2/Controller/FileWriter.cs
> +        public void Serialize(string path, object json)
Алина, разберитесь, почему код не билдится. Учитывая момент с отсутствием файла проекта, возможно у Вам не настроен правильно файл .gitignore, потому что нужные файлы не попадают в коммит. 
![unildable_state](https://user-images.githubusercontent.com/69808191/91526968-79785f80-e90d-11ea-8e77-9d687c979a7c.jpg)

2020-08-28 06:17 UTC, serhii-shkodenko commented on task2/Controller/FileWriter.cs
> +    public class FileWriter
Имеет смысл здесь реализовать интерфейс, и зависеть в на более высоких уровнях от него, а не от Вашей реализации.

2020-08-28 06:17 UTC, serhii-shkodenko commented on task2/Controller/AllIngredients.cs
> +    public class AllIngredients
Если поместили файл в папку с контроллерами, так и назовите класс. Например `IngredientsController`.

2020-08-28 06:17 UTC, serhii-shkodenko commented on task2/Controller/AllIngredients.cs
> +        private  FileWriter _fileWriter = new FileWriter();
Здесь Вы зависете от объекта с типом FileWriter, лучше зависить от его абстракции. Ваш код было бы представить, например, в таком виде. 

    public class IngredientsController
    {
        private readonly IFileWriter _fileWriter;

        public IngredientsController(IFileWriter fileWriter)
        {
            _fileWriter = fileWriter;
        }

        public void UpdateIngridients(Dictionary<string, string> currentIngredients, string directoryPath)
        {
            var allFromJson = JsonConvert.DeserializeObject<Dictionary<string, string>>(File.ReadAllText(directoryPath));        
            currentIngredients.ToList().ForEach(x => allFromJson.Add(x.Key, x.Value));
            _fileWriter.Serialize(directoryPath, allFromJson);
        }
    }

Однако, учитывая, что это контроллер, он должен зависеть от объекта IUnitOfWork. Логика работы с файловой системой должна находиться за репозиторием, ниже него. Репозиторий призван скрыть от потребителя эту деталь. Пожалуйста, реализуйте паттерны UnitOfWork и Repository.

2020-08-28 07:28 UTC, serhii-shkodenko requested changes

2020-08-28 07:28 UTC, serhii-shkodenko commented on task2/Controller/FileWriter.cs
> +    public class FileWriter
Класс с названием `FileWriter` не следует размещать в папке `Controller`.

2020-09-03 14:45 UTC, alex-geraschenko commented
Вы уверены, что добавили репозитории? Я по коммиту вижу, что Вы только удалили файлы и все

2020-09-03 15:25 UTC, alinashev commented
> Вы уверены, что добавили репозитории? Я по коммиту вижу, что Вы только удалили файлы и все
Добрый вечер, все исправила, проверьте, пожалуйста

2020-09-07 18:54 UTC, alex-geraschenko requested changes
**Repository** и **UnitOfWork** реализованы некорректно. Посмотрите пример тут https://www.infoworld.com/article/3107186/how-to-implement-the-repository-design-pattern-in-c.html
https://uk.wikipedia.org/wiki/Unit_Of_Work

2020-09-07 18:54 UTC, alex-geraschenko commented on task2/Controller/Action/MoveAddRecipe.cs
> +    public class MoveAddRecipe : IAction
Имена классов должны быть существительными и отражать назначение класса. Сейчас не понятно, для чего этот класс

2020-09-07 18:54 UTC, alex-geraschenko commented on task2/Controller/Action/MoveAddRecipe.cs
> +        private RepositoryController _repositoryController = new RepositoryController();
Нарушение принципа **Dependency Inversion**

2020-09-07 18:54 UTC, alex-geraschenko commented on task2/Controller/Print.cs
> +    public class Print
Имена классов должны быть существительными и отражать назначение класса. Сейчас не понятно, для чего этот класс

2020-09-07 18:54 UTC, alex-geraschenko commented on task2/Controller/RecipeController/NewRecipe.cs
> +   public class NewRecipe
Имена классов должны быть существительными и отражать назначение класса. Сейчас не понятно, для чего этот класс

2020-09-07 18:54 UTC, alex-geraschenko commented on task2/Controller/RecipeController/PathRecipe.cs
> +                        name = _newrecipe.AddName();
Делать отдельный файл для каждого рецепта плохая идея. Лучше хранить все рецепты в одном файле в виде списка

2020-09-07 18:54 UTC, alex-geraschenko commented on task2/Controller/RecipeController/UpdaterAllIngredients.cs
> +    public class UpdaterAllIngredients
Имена классов должны быть существительными и отражать назначение класса. Сейчас не понятно, для чего этот класс

2020-09-07 18:54 UTC, alex-geraschenko commented on task2/Controller/RepositoryController.cs
> +    public class RepositoryController : IRepository
Не совсем понял это **Репозиторий** или это **Контроллер**?

2020-09-07 18:54 UTC, alex-geraschenko commented on task2/Interface/IAction.cs
> +        public void ToDo(string directoryName);
В интерфейсах все методы и свойства уже публичны. Дополнительно это указывать не нужно

2020-09-07 18:54 UTC, alex-geraschenko commented on task2/Interface/IRepository.cs
> +        public void Add(string directoryName);
В интерфейсах все методы и свойства уже публичны. Дополнительно это указывать не нужно

2020-09-07 18:54 UTC, alex-geraschenko commented on task2/Model/Ingredient.cs
> +        public  Dictionary <string, string> dictionaryIngredients { get; set;} = new Dictionary<string, string>();
Вместо `dictionaryIngredients` лучше назвать свойство `Ingredients`

2021-11-10 20:23 UTC, closed without merging